// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listcategoryproductprotpcpl.proto

package com.example.tutorial;

public final class ListCategoryProductProtocol {
  private ListCategoryProductProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListCategoryProductItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 userId = 1;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();

    // optional int32 os = 2;
    /**
     * <code>optional int32 os = 2;</code>
     */
    boolean hasOs();
    /**
     * <code>optional int32 os = 2;</code>
     */
    int getOs();

    // optional int32 size = 3;
    /**
     * <code>optional int32 size = 3;</code>
     */
    boolean hasSize();
    /**
     * <code>optional int32 size = 3;</code>
     */
    int getSize();

    // optional int32 start = 4;
    /**
     * <code>optional int32 start = 4;</code>
     */
    boolean hasStart();
    /**
     * <code>optional int32 start = 4;</code>
     */
    int getStart();

    // optional string mobile = 5;
    /**
     * <code>optional string mobile = 5;</code>
     */
    boolean hasMobile();
    /**
     * <code>optional string mobile = 5;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 5;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    // optional int32 orderBy = 6;
    /**
     * <code>optional int32 orderBy = 6;</code>
     */
    boolean hasOrderBy();
    /**
     * <code>optional int32 orderBy = 6;</code>
     */
    int getOrderBy();

    // optional int32 categoryId = 7;
    /**
     * <code>optional int32 categoryId = 7;</code>
     */
    boolean hasCategoryId();
    /**
     * <code>optional int32 categoryId = 7;</code>
     */
    int getCategoryId();

    // optional int32 themeVersion = 8;
    /**
     * <code>optional int32 themeVersion = 8;</code>
     */
    boolean hasThemeVersion();
    /**
     * <code>optional int32 themeVersion = 8;</code>
     */
    int getThemeVersion();

    // optional int32 platform = 9;
    /**
     * <code>optional int32 platform = 9;</code>
     */
    boolean hasPlatform();
    /**
     * <code>optional int32 platform = 9;</code>
     */
    int getPlatform();

    // optional int32 compress = 10;
    /**
     * <code>optional int32 compress = 10;</code>
     */
    boolean hasCompress();
    /**
     * <code>optional int32 compress = 10;</code>
     */
    int getCompress();

    // optional int32 resType = 11;
    /**
     * <code>optional int32 resType = 11;</code>
     */
    boolean hasResType();
    /**
     * <code>optional int32 resType = 11;</code>
     */
    int getResType();

    // optional int64 relateId = 12;
    /**
     * <code>optional int64 relateId = 12;</code>
     */
    boolean hasRelateId();
    /**
     * <code>optional int64 relateId = 12;</code>
     */
    long getRelateId();

    // optional string keyword = 13;
    /**
     * <code>optional string keyword = 13;</code>
     */
    boolean hasKeyword();
    /**
     * <code>optional string keyword = 13;</code>
     */
    java.lang.String getKeyword();
    /**
     * <code>optional string keyword = 13;</code>
     */
    com.google.protobuf.ByteString
        getKeywordBytes();

    // optional string screen = 14;
    /**
     * <code>optional string screen = 14;</code>
     */
    boolean hasScreen();
    /**
     * <code>optional string screen = 14;</code>
     */
    java.lang.String getScreen();
    /**
     * <code>optional string screen = 14;</code>
     */
    com.google.protobuf.ByteString
        getScreenBytes();

    // optional int32 source = 15;
    /**
     * <code>optional int32 source = 15;</code>
     */
    boolean hasSource();
    /**
     * <code>optional int32 source = 15;</code>
     */
    int getSource();

    // optional string userToken = 16;
    /**
     * <code>optional string userToken = 16;</code>
     */
    boolean hasUserToken();
    /**
     * <code>optional string userToken = 16;</code>
     */
    java.lang.String getUserToken();
    /**
     * <code>optional string userToken = 16;</code>
     */
    com.google.protobuf.ByteString
        getUserTokenBytes();

    // optional int32 randomCount = 17;
    /**
     * <code>optional int32 randomCount = 17;</code>
     */
    boolean hasRandomCount();
    /**
     * <code>optional int32 randomCount = 17;</code>
     */
    int getRandomCount();

    // optional string imei = 18;
    /**
     * <code>optional string imei = 18;</code>
     */
    boolean hasImei();
    /**
     * <code>optional string imei = 18;</code>
     */
    java.lang.String getImei();
    /**
     * <code>optional string imei = 18;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    // optional int32 searchType = 19;
    /**
     * <code>optional int32 searchType = 19;</code>
     */
    boolean hasSearchType();
    /**
     * <code>optional int32 searchType = 19;</code>
     */
    int getSearchType();

    // optional string imsi = 20;
    /**
     * <code>optional string imsi = 20;</code>
     */
    boolean hasImsi();
    /**
     * <code>optional string imsi = 20;</code>
     */
    java.lang.String getImsi();
    /**
     * <code>optional string imsi = 20;</code>
     */
    com.google.protobuf.ByteString
        getImsiBytes();

    // optional string net = 21;
    /**
     * <code>optional string net = 21;</code>
     */
    boolean hasNet();
    /**
     * <code>optional string net = 21;</code>
     */
    java.lang.String getNet();
    /**
     * <code>optional string net = 21;</code>
     */
    com.google.protobuf.ByteString
        getNetBytes();
  }
  /**
   * Protobuf type {@code tutorial.ListCategoryProductItem}
   */
  public static final class ListCategoryProductItem extends
      com.google.protobuf.GeneratedMessage
      implements ListCategoryProductItemOrBuilder {
    // Use ListCategoryProductItem.newBuilder() to construct.
    private ListCategoryProductItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListCategoryProductItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListCategoryProductItem defaultInstance;
    public static ListCategoryProductItem getDefaultInstance() {
      return defaultInstance;
    }

    public ListCategoryProductItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListCategoryProductItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              os_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              start_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              mobile_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              orderBy_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              categoryId_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              themeVersion_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              platform_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              compress_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              resType_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              relateId_ = input.readInt64();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              keyword_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              screen_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              source_ = input.readInt32();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              userToken_ = input.readBytes();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              randomCount_ = input.readInt32();
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              imei_ = input.readBytes();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              searchType_ = input.readInt32();
              break;
            }
            case 162: {
              bitField0_ |= 0x00080000;
              imsi_ = input.readBytes();
              break;
            }
            case 170: {
              bitField0_ |= 0x00100000;
              net_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ListCategoryProductProtocol.internal_static_tutorial_ListCategoryProductItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ListCategoryProductProtocol.internal_static_tutorial_ListCategoryProductItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.class, com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.Builder.class);
    }

    public static com.google.protobuf.Parser<ListCategoryProductItem> PARSER =
        new com.google.protobuf.AbstractParser<ListCategoryProductItem>() {
      public ListCategoryProductItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListCategoryProductItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListCategoryProductItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 os = 2;
    public static final int OS_FIELD_NUMBER = 2;
    private int os_;
    /**
     * <code>optional int32 os = 2;</code>
     */
    public boolean hasOs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 os = 2;</code>
     */
    public int getOs() {
      return os_;
    }

    // optional int32 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>optional int32 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    // optional int32 start = 4;
    public static final int START_FIELD_NUMBER = 4;
    private int start_;
    /**
     * <code>optional int32 start = 4;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 start = 4;</code>
     */
    public int getStart() {
      return start_;
    }

    // optional string mobile = 5;
    public static final int MOBILE_FIELD_NUMBER = 5;
    private java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 5;</code>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string mobile = 5;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mobile = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 orderBy = 6;
    public static final int ORDERBY_FIELD_NUMBER = 6;
    private int orderBy_;
    /**
     * <code>optional int32 orderBy = 6;</code>
     */
    public boolean hasOrderBy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 orderBy = 6;</code>
     */
    public int getOrderBy() {
      return orderBy_;
    }

    // optional int32 categoryId = 7;
    public static final int CATEGORYID_FIELD_NUMBER = 7;
    private int categoryId_;
    /**
     * <code>optional int32 categoryId = 7;</code>
     */
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 categoryId = 7;</code>
     */
    public int getCategoryId() {
      return categoryId_;
    }

    // optional int32 themeVersion = 8;
    public static final int THEMEVERSION_FIELD_NUMBER = 8;
    private int themeVersion_;
    /**
     * <code>optional int32 themeVersion = 8;</code>
     */
    public boolean hasThemeVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 themeVersion = 8;</code>
     */
    public int getThemeVersion() {
      return themeVersion_;
    }

    // optional int32 platform = 9;
    public static final int PLATFORM_FIELD_NUMBER = 9;
    private int platform_;
    /**
     * <code>optional int32 platform = 9;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 platform = 9;</code>
     */
    public int getPlatform() {
      return platform_;
    }

    // optional int32 compress = 10;
    public static final int COMPRESS_FIELD_NUMBER = 10;
    private int compress_;
    /**
     * <code>optional int32 compress = 10;</code>
     */
    public boolean hasCompress() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 compress = 10;</code>
     */
    public int getCompress() {
      return compress_;
    }

    // optional int32 resType = 11;
    public static final int RESTYPE_FIELD_NUMBER = 11;
    private int resType_;
    /**
     * <code>optional int32 resType = 11;</code>
     */
    public boolean hasResType() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 resType = 11;</code>
     */
    public int getResType() {
      return resType_;
    }

    // optional int64 relateId = 12;
    public static final int RELATEID_FIELD_NUMBER = 12;
    private long relateId_;
    /**
     * <code>optional int64 relateId = 12;</code>
     */
    public boolean hasRelateId() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 relateId = 12;</code>
     */
    public long getRelateId() {
      return relateId_;
    }

    // optional string keyword = 13;
    public static final int KEYWORD_FIELD_NUMBER = 13;
    private java.lang.Object keyword_;
    /**
     * <code>optional string keyword = 13;</code>
     */
    public boolean hasKeyword() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string keyword = 13;</code>
     */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          keyword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string keyword = 13;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string screen = 14;
    public static final int SCREEN_FIELD_NUMBER = 14;
    private java.lang.Object screen_;
    /**
     * <code>optional string screen = 14;</code>
     */
    public boolean hasScreen() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string screen = 14;</code>
     */
    public java.lang.String getScreen() {
      java.lang.Object ref = screen_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          screen_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string screen = 14;</code>
     */
    public com.google.protobuf.ByteString
        getScreenBytes() {
      java.lang.Object ref = screen_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        screen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 source = 15;
    public static final int SOURCE_FIELD_NUMBER = 15;
    private int source_;
    /**
     * <code>optional int32 source = 15;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 source = 15;</code>
     */
    public int getSource() {
      return source_;
    }

    // optional string userToken = 16;
    public static final int USERTOKEN_FIELD_NUMBER = 16;
    private java.lang.Object userToken_;
    /**
     * <code>optional string userToken = 16;</code>
     */
    public boolean hasUserToken() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string userToken = 16;</code>
     */
    public java.lang.String getUserToken() {
      java.lang.Object ref = userToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userToken = 16;</code>
     */
    public com.google.protobuf.ByteString
        getUserTokenBytes() {
      java.lang.Object ref = userToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 randomCount = 17;
    public static final int RANDOMCOUNT_FIELD_NUMBER = 17;
    private int randomCount_;
    /**
     * <code>optional int32 randomCount = 17;</code>
     */
    public boolean hasRandomCount() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int32 randomCount = 17;</code>
     */
    public int getRandomCount() {
      return randomCount_;
    }

    // optional string imei = 18;
    public static final int IMEI_FIELD_NUMBER = 18;
    private java.lang.Object imei_;
    /**
     * <code>optional string imei = 18;</code>
     */
    public boolean hasImei() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string imei = 18;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imei_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imei = 18;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 searchType = 19;
    public static final int SEARCHTYPE_FIELD_NUMBER = 19;
    private int searchType_;
    /**
     * <code>optional int32 searchType = 19;</code>
     */
    public boolean hasSearchType() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional int32 searchType = 19;</code>
     */
    public int getSearchType() {
      return searchType_;
    }

    // optional string imsi = 20;
    public static final int IMSI_FIELD_NUMBER = 20;
    private java.lang.Object imsi_;
    /**
     * <code>optional string imsi = 20;</code>
     */
    public boolean hasImsi() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional string imsi = 20;</code>
     */
    public java.lang.String getImsi() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imsi_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imsi = 20;</code>
     */
    public com.google.protobuf.ByteString
        getImsiBytes() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imsi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string net = 21;
    public static final int NET_FIELD_NUMBER = 21;
    private java.lang.Object net_;
    /**
     * <code>optional string net = 21;</code>
     */
    public boolean hasNet() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional string net = 21;</code>
     */
    public java.lang.String getNet() {
      java.lang.Object ref = net_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          net_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string net = 21;</code>
     */
    public com.google.protobuf.ByteString
        getNetBytes() {
      java.lang.Object ref = net_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        net_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = 0;
      os_ = 0;
      size_ = 0;
      start_ = 0;
      mobile_ = "";
      orderBy_ = 0;
      categoryId_ = 0;
      themeVersion_ = 0;
      platform_ = 0;
      compress_ = 0;
      resType_ = 0;
      relateId_ = 0L;
      keyword_ = "";
      screen_ = "";
      source_ = 0;
      userToken_ = "";
      randomCount_ = 0;
      imei_ = "";
      searchType_ = 0;
      imsi_ = "";
      net_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, os_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMobileBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, orderBy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, categoryId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, themeVersion_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, platform_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, compress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, resType_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, relateId_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getKeywordBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getScreenBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, source_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, randomCount_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getImeiBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(19, searchType_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(20, getImsiBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, getNetBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, os_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMobileBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, orderBy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, categoryId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, themeVersion_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, platform_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, compress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, resType_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, relateId_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getKeywordBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getScreenBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, source_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, randomCount_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getImeiBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, searchType_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getImsiBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, getNetBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ListCategoryProductItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ListCategoryProductProtocol.internal_static_tutorial_ListCategoryProductItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ListCategoryProductProtocol.internal_static_tutorial_ListCategoryProductItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.class, com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.Builder.class);
      }

      // Construct using com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        os_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        orderBy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        categoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        themeVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        platform_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        compress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        resType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        relateId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        keyword_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        screen_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        source_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        userToken_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        randomCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        searchType_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        imsi_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        net_ = "";
        bitField0_ = (bitField0_ & ~0x00100000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ListCategoryProductProtocol.internal_static_tutorial_ListCategoryProductItem_descriptor;
      }

      public com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem getDefaultInstanceForType() {
        return com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.getDefaultInstance();
      }

      public com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem build() {
        com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem buildPartial() {
        com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem result = new com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.orderBy_ = orderBy_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.categoryId_ = categoryId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.themeVersion_ = themeVersion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.compress_ = compress_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.resType_ = resType_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.relateId_ = relateId_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.keyword_ = keyword_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.screen_ = screen_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.userToken_ = userToken_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.randomCount_ = randomCount_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.searchType_ = searchType_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.imsi_ = imsi_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.net_ = net_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem) {
          return mergeFrom((com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem other) {
        if (other == com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasMobile()) {
          bitField0_ |= 0x00000010;
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.hasOrderBy()) {
          setOrderBy(other.getOrderBy());
        }
        if (other.hasCategoryId()) {
          setCategoryId(other.getCategoryId());
        }
        if (other.hasThemeVersion()) {
          setThemeVersion(other.getThemeVersion());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasCompress()) {
          setCompress(other.getCompress());
        }
        if (other.hasResType()) {
          setResType(other.getResType());
        }
        if (other.hasRelateId()) {
          setRelateId(other.getRelateId());
        }
        if (other.hasKeyword()) {
          bitField0_ |= 0x00001000;
          keyword_ = other.keyword_;
          onChanged();
        }
        if (other.hasScreen()) {
          bitField0_ |= 0x00002000;
          screen_ = other.screen_;
          onChanged();
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasUserToken()) {
          bitField0_ |= 0x00008000;
          userToken_ = other.userToken_;
          onChanged();
        }
        if (other.hasRandomCount()) {
          setRandomCount(other.getRandomCount());
        }
        if (other.hasImei()) {
          bitField0_ |= 0x00020000;
          imei_ = other.imei_;
          onChanged();
        }
        if (other.hasSearchType()) {
          setSearchType(other.getSearchType());
        }
        if (other.hasImsi()) {
          bitField0_ |= 0x00080000;
          imsi_ = other.imsi_;
          onChanged();
        }
        if (other.hasNet()) {
          bitField0_ |= 0x00100000;
          net_ = other.net_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial.ListCategoryProductProtocol.ListCategoryProductItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 userId = 1;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 os = 2;
      private int os_ ;
      /**
       * <code>optional int32 os = 2;</code>
       */
      public boolean hasOs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 os = 2;</code>
       */
      public int getOs() {
        return os_;
      }
      /**
       * <code>optional int32 os = 2;</code>
       */
      public Builder setOs(int value) {
        bitField0_ |= 0x00000002;
        os_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 os = 2;</code>
       */
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        os_ = 0;
        onChanged();
        return this;
      }

      // optional int32 size = 3;
      private int size_ ;
      /**
       * <code>optional int32 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }

      // optional int32 start = 4;
      private int start_ ;
      /**
       * <code>optional int32 start = 4;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public Builder setStart(int value) {
        bitField0_ |= 0x00000008;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        start_ = 0;
        onChanged();
        return this;
      }

      // optional string mobile = 5;
      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 5;</code>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string mobile = 5;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 5;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 5;</code>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 5;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mobile_ = value;
        onChanged();
        return this;
      }

      // optional int32 orderBy = 6;
      private int orderBy_ ;
      /**
       * <code>optional int32 orderBy = 6;</code>
       */
      public boolean hasOrderBy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 orderBy = 6;</code>
       */
      public int getOrderBy() {
        return orderBy_;
      }
      /**
       * <code>optional int32 orderBy = 6;</code>
       */
      public Builder setOrderBy(int value) {
        bitField0_ |= 0x00000020;
        orderBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 orderBy = 6;</code>
       */
      public Builder clearOrderBy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        orderBy_ = 0;
        onChanged();
        return this;
      }

      // optional int32 categoryId = 7;
      private int categoryId_ ;
      /**
       * <code>optional int32 categoryId = 7;</code>
       */
      public boolean hasCategoryId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 categoryId = 7;</code>
       */
      public int getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>optional int32 categoryId = 7;</code>
       */
      public Builder setCategoryId(int value) {
        bitField0_ |= 0x00000040;
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 categoryId = 7;</code>
       */
      public Builder clearCategoryId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        categoryId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 themeVersion = 8;
      private int themeVersion_ ;
      /**
       * <code>optional int32 themeVersion = 8;</code>
       */
      public boolean hasThemeVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 themeVersion = 8;</code>
       */
      public int getThemeVersion() {
        return themeVersion_;
      }
      /**
       * <code>optional int32 themeVersion = 8;</code>
       */
      public Builder setThemeVersion(int value) {
        bitField0_ |= 0x00000080;
        themeVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 themeVersion = 8;</code>
       */
      public Builder clearThemeVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        themeVersion_ = 0;
        onChanged();
        return this;
      }

      // optional int32 platform = 9;
      private int platform_ ;
      /**
       * <code>optional int32 platform = 9;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 platform = 9;</code>
       */
      public int getPlatform() {
        return platform_;
      }
      /**
       * <code>optional int32 platform = 9;</code>
       */
      public Builder setPlatform(int value) {
        bitField0_ |= 0x00000100;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 platform = 9;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000100);
        platform_ = 0;
        onChanged();
        return this;
      }

      // optional int32 compress = 10;
      private int compress_ ;
      /**
       * <code>optional int32 compress = 10;</code>
       */
      public boolean hasCompress() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 compress = 10;</code>
       */
      public int getCompress() {
        return compress_;
      }
      /**
       * <code>optional int32 compress = 10;</code>
       */
      public Builder setCompress(int value) {
        bitField0_ |= 0x00000200;
        compress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 compress = 10;</code>
       */
      public Builder clearCompress() {
        bitField0_ = (bitField0_ & ~0x00000200);
        compress_ = 0;
        onChanged();
        return this;
      }

      // optional int32 resType = 11;
      private int resType_ ;
      /**
       * <code>optional int32 resType = 11;</code>
       */
      public boolean hasResType() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 resType = 11;</code>
       */
      public int getResType() {
        return resType_;
      }
      /**
       * <code>optional int32 resType = 11;</code>
       */
      public Builder setResType(int value) {
        bitField0_ |= 0x00000400;
        resType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resType = 11;</code>
       */
      public Builder clearResType() {
        bitField0_ = (bitField0_ & ~0x00000400);
        resType_ = 0;
        onChanged();
        return this;
      }

      // optional int64 relateId = 12;
      private long relateId_ ;
      /**
       * <code>optional int64 relateId = 12;</code>
       */
      public boolean hasRelateId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 relateId = 12;</code>
       */
      public long getRelateId() {
        return relateId_;
      }
      /**
       * <code>optional int64 relateId = 12;</code>
       */
      public Builder setRelateId(long value) {
        bitField0_ |= 0x00000800;
        relateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 relateId = 12;</code>
       */
      public Builder clearRelateId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        relateId_ = 0L;
        onChanged();
        return this;
      }

      // optional string keyword = 13;
      private java.lang.Object keyword_ = "";
      /**
       * <code>optional string keyword = 13;</code>
       */
      public boolean hasKeyword() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string keyword = 13;</code>
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string keyword = 13;</code>
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string keyword = 13;</code>
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string keyword = 13;</code>
       */
      public Builder clearKeyword() {
        bitField0_ = (bitField0_ & ~0x00001000);
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string keyword = 13;</code>
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        keyword_ = value;
        onChanged();
        return this;
      }

      // optional string screen = 14;
      private java.lang.Object screen_ = "";
      /**
       * <code>optional string screen = 14;</code>
       */
      public boolean hasScreen() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string screen = 14;</code>
       */
      public java.lang.String getScreen() {
        java.lang.Object ref = screen_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          screen_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string screen = 14;</code>
       */
      public com.google.protobuf.ByteString
          getScreenBytes() {
        java.lang.Object ref = screen_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          screen_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string screen = 14;</code>
       */
      public Builder setScreen(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        screen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string screen = 14;</code>
       */
      public Builder clearScreen() {
        bitField0_ = (bitField0_ & ~0x00002000);
        screen_ = getDefaultInstance().getScreen();
        onChanged();
        return this;
      }
      /**
       * <code>optional string screen = 14;</code>
       */
      public Builder setScreenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        screen_ = value;
        onChanged();
        return this;
      }

      // optional int32 source = 15;
      private int source_ ;
      /**
       * <code>optional int32 source = 15;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 source = 15;</code>
       */
      public int getSource() {
        return source_;
      }
      /**
       * <code>optional int32 source = 15;</code>
       */
      public Builder setSource(int value) {
        bitField0_ |= 0x00004000;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 source = 15;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00004000);
        source_ = 0;
        onChanged();
        return this;
      }

      // optional string userToken = 16;
      private java.lang.Object userToken_ = "";
      /**
       * <code>optional string userToken = 16;</code>
       */
      public boolean hasUserToken() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string userToken = 16;</code>
       */
      public java.lang.String getUserToken() {
        java.lang.Object ref = userToken_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userToken = 16;</code>
       */
      public com.google.protobuf.ByteString
          getUserTokenBytes() {
        java.lang.Object ref = userToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userToken = 16;</code>
       */
      public Builder setUserToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        userToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userToken = 16;</code>
       */
      public Builder clearUserToken() {
        bitField0_ = (bitField0_ & ~0x00008000);
        userToken_ = getDefaultInstance().getUserToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userToken = 16;</code>
       */
      public Builder setUserTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        userToken_ = value;
        onChanged();
        return this;
      }

      // optional int32 randomCount = 17;
      private int randomCount_ ;
      /**
       * <code>optional int32 randomCount = 17;</code>
       */
      public boolean hasRandomCount() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int32 randomCount = 17;</code>
       */
      public int getRandomCount() {
        return randomCount_;
      }
      /**
       * <code>optional int32 randomCount = 17;</code>
       */
      public Builder setRandomCount(int value) {
        bitField0_ |= 0x00010000;
        randomCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 randomCount = 17;</code>
       */
      public Builder clearRandomCount() {
        bitField0_ = (bitField0_ & ~0x00010000);
        randomCount_ = 0;
        onChanged();
        return this;
      }

      // optional string imei = 18;
      private java.lang.Object imei_ = "";
      /**
       * <code>optional string imei = 18;</code>
       */
      public boolean hasImei() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional string imei = 18;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imei = 18;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imei = 18;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 18;</code>
       */
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00020000);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 18;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        imei_ = value;
        onChanged();
        return this;
      }

      // optional int32 searchType = 19;
      private int searchType_ ;
      /**
       * <code>optional int32 searchType = 19;</code>
       */
      public boolean hasSearchType() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional int32 searchType = 19;</code>
       */
      public int getSearchType() {
        return searchType_;
      }
      /**
       * <code>optional int32 searchType = 19;</code>
       */
      public Builder setSearchType(int value) {
        bitField0_ |= 0x00040000;
        searchType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 searchType = 19;</code>
       */
      public Builder clearSearchType() {
        bitField0_ = (bitField0_ & ~0x00040000);
        searchType_ = 0;
        onChanged();
        return this;
      }

      // optional string imsi = 20;
      private java.lang.Object imsi_ = "";
      /**
       * <code>optional string imsi = 20;</code>
       */
      public boolean hasImsi() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional string imsi = 20;</code>
       */
      public java.lang.String getImsi() {
        java.lang.Object ref = imsi_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imsi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imsi = 20;</code>
       */
      public com.google.protobuf.ByteString
          getImsiBytes() {
        java.lang.Object ref = imsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imsi = 20;</code>
       */
      public Builder setImsi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        imsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imsi = 20;</code>
       */
      public Builder clearImsi() {
        bitField0_ = (bitField0_ & ~0x00080000);
        imsi_ = getDefaultInstance().getImsi();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imsi = 20;</code>
       */
      public Builder setImsiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        imsi_ = value;
        onChanged();
        return this;
      }

      // optional string net = 21;
      private java.lang.Object net_ = "";
      /**
       * <code>optional string net = 21;</code>
       */
      public boolean hasNet() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional string net = 21;</code>
       */
      public java.lang.String getNet() {
        java.lang.Object ref = net_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          net_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string net = 21;</code>
       */
      public com.google.protobuf.ByteString
          getNetBytes() {
        java.lang.Object ref = net_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          net_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string net = 21;</code>
       */
      public Builder setNet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        net_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string net = 21;</code>
       */
      public Builder clearNet() {
        bitField0_ = (bitField0_ & ~0x00100000);
        net_ = getDefaultInstance().getNet();
        onChanged();
        return this;
      }
      /**
       * <code>optional string net = 21;</code>
       */
      public Builder setNetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        net_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.ListCategoryProductItem)
    }

    static {
      defaultInstance = new ListCategoryProductItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.ListCategoryProductItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ListCategoryProductItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ListCategoryProductItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!listcategoryproductprotpcpl.proto\022\010tut" +
      "orial\"\372\002\n\027ListCategoryProductItem\022\016\n\006use" +
      "rId\030\001 \001(\005\022\n\n\002os\030\002 \001(\005\022\014\n\004size\030\003 \001(\005\022\r\n\005s" +
      "tart\030\004 \001(\005\022\016\n\006mobile\030\005 \001(\t\022\017\n\007orderBy\030\006 " +
      "\001(\005\022\022\n\ncategoryId\030\007 \001(\005\022\024\n\014themeVersion\030" +
      "\010 \001(\005\022\020\n\010platform\030\t \001(\005\022\020\n\010compress\030\n \001(" +
      "\005\022\017\n\007resType\030\013 \001(\005\022\020\n\010relateId\030\014 \001(\003\022\017\n\007" +
      "keyword\030\r \001(\t\022\016\n\006screen\030\016 \001(\t\022\016\n\006source\030" +
      "\017 \001(\005\022\021\n\tuserToken\030\020 \001(\t\022\023\n\013randomCount\030" +
      "\021 \001(\005\022\014\n\004imei\030\022 \001(\t\022\022\n\nsearchType\030\023 \001(\005\022",
      "\014\n\004imsi\030\024 \001(\t\022\013\n\003net\030\025 \001(\tB3\n\024com.exampl" +
      "e.tutorialB\033ListCategoryProductProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_ListCategoryProductItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_ListCategoryProductItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_ListCategoryProductItem_descriptor,
              new java.lang.String[] { "UserId", "Os", "Size", "Start", "Mobile", "OrderBy", "CategoryId", "ThemeVersion", "Platform", "Compress", "ResType", "RelateId", "Keyword", "Screen", "Source", "UserToken", "RandomCount", "Imei", "SearchType", "Imsi", "Net", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
